apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ordera
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 405087531929.dkr.ecr.us-east-1.amazonaws.com/ordera-app:frontend-4455320f4ecff7777c5633dc70bd27e3efc570a8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m" # Adjusted CPU limits for frontend to better reflect its expected load and ensure efficient resource utilization.