stringData:
  DATABASE_URL: "postgresql://raguser:Upendra143Test@ordera-postgres.csju4m04qc7w.us-east-1.rds.amazonaws.com:5432/restaurant_agent"
  DB_HOST: "ordera-postgres.csju4m04qc7w.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "restaurant_agent"
  DB_USER: "raguser"
  DB_PASSWORD: "Upendra143Test"
  FRONTEND_URL: "http://REPLACE_AFTER_ALB_CREATED"